### ISSUE TITLE
Build fail for missing files

### ISSUE THREAD

**Issue by Dandelight** [Lakr233/Axchange#3]
Thank your for building this software. I've been looking for a Android - macOS file transfer file for a while. I'd like to build it locally but Xcode gave this error:

<img width="994" alt="image" src="https://github.com/user-attachments/assets/54bf0c56-f35c-4b64-9312-d7046ef5bacc" />

Following the instructions, I found that the following (red) files are not present in this repository:

<img width="299" alt="image" src="https://github.com/user-attachments/assets/d22eab12-7cf2-4909-b91f-99243eee43a6" />

I also noticed that this app can be purchased from App Store or [Digita Lychee](https://lizhi.shop/site/products/id/791). Does this mean that this project is not full open-source?

Thank you for your attention to this issue!

**Comment by Lakr233** [comment]
This project is fullly open sourced. Those script are for convenience embedding ADB binary and including my personal signing certificates. You are on your own to build one and pack it into Axchange.

**Comment by Dandelight** [comment]
> This project is fullly open sourced. Those script are for convenience embedding ADB binary and including my personal signing certificates which can not be shared with. With that said, you are on your own to build one and pack it into Axchange. It would take under 5 minutes for experienced developers.

Thanks for your reply. I may not be as experienced, but at last I figured out the correct configuration. The app is elegant, and so is the code. Great thanks for the effort you've put into it.

**Comment by luciodaou** [comment]
> > This project is fullly open sourced. Those script are for convenience embedding ADB binary and including my personal signing certificates which can not be shared with. With that said, you are on your own to build one and pack it into Axchange. It would take under 5 minutes for experienced developers.
> 
> Thanks for your reply. I may not be as experienced, but at last I figured out the correct configuration. The app is elegant, and so is the code. Great thanks for the effort you've put into it.

Hi, would you mind sharing some details? I'm a complete newbie to Xcode, and I'm having a hard time trying to build the app.

**Comment by Lakr233** [comment]
> > > This project is fullly open sourced. Those script are for convenience embedding ADB binary and including my personal signing certificates which can not be shared with. With that said, you are on your own to build one and pack it into Axchange. It would take under 5 minutes for experienced developers.
> > 
> > 
> > Thanks for your reply. I may not be as experienced, but at last I figured out the correct configuration. The app is elegant, and so is the code. Great thanks for the effort you've put into it.
> 
> Hi, would you mind sharing some details? I'm a complete newbie to Xcode, and I'm having a hard time trying to build the app.

Probably ask claude-code for help. They can do it within one shot.
